name: shetech-sweetstyle
version: 0.1.0
summary: Snap Application to Demonstrate SnapCraft for SheTech-2019
description: |
        This application takes text as input
        and provides a fancy output.
confinement: devmode
base: core18
parts:
        shetech-sweetstyle:
                source: .
                plugin: dump
                stage-packages: [ boxes, cowsay, fortune ]
                #                filesets:
                #                        programs: [ usr/share/*, usr/bin/*, usr/games/* ]
                #                stage:
                #                        - $programs
layout:
        /usr/games:
                bind: $SNAP/usr/games
        /usr/share:
                bind: $SNAP/usr/share
apps:
        shetech-sweetstyle:
                command: bin/shetech-sweetstyle
